server:
  port: 8080
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  # prefix: /api # 添加路由前缀
  retryable: true
  routes:
    user-service: /api-user/** # 路由映射
    product-service: /api-product/**
    order-service: /api-order/**
    auth-service: /api-auth/**
    file-service: /api-file/**
    type-service: /api-type/**
    car-service: /api-car/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**


ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

auth:
  shopUrl:
  adminUrl: /api-user/user/get,/api-order/order/set,/api-order/order/get
  userUrl: /api-order/order/get,/api-order/order/save,/api-order/order/count